# Generated by Django 3.1.7 on 2021-05-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
